BEGIN;

CREATE TABLE activity (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL CHECK (BTRIM(name) <> ''),
    default_type VARCHAR(40) NOT NULL CHECK (
        default_type IN ('TEACHING', 'COMPANION_READING', 'PLAY', 'DAILY_INTERACTION', 'PASSIVE')
    ),
    sort_order INTEGER NOT NULL CHECK (sort_order > 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE OR REPLACE FUNCTION set_activity_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER activity_updated_at_trigger
BEFORE UPDATE ON activity
FOR EACH ROW
EXECUTE FUNCTION set_activity_updated_at();

CREATE TABLE activity_type_color (
    default_type VARCHAR(40) PRIMARY KEY CHECK (
        default_type IN ('TEACHING', 'COMPANION_READING', 'PLAY', 'DAILY_INTERACTION', 'PASSIVE')
    ),
    tag_color VARCHAR(7) NOT NULL CHECK (tag_color ~ '^#[0-9A-Fa-f]{6}$')
);

INSERT INTO activity_type_color (default_type, tag_color)
VALUES
    ('TEACHING', '#2563EB'),
    ('COMPANION_READING', '#7C3AED'),
    ('PLAY', '#EA580C'),
    ('DAILY_INTERACTION', '#059669'),
    ('PASSIVE', '#64748B');

COMMIT;
