BEGIN;

CREATE TABLE record_setting (
    setting_id SMALLINT PRIMARY KEY CHECK (setting_id = 1),
    default_year INTEGER NOT NULL CHECK (default_year BETWEEN 2000 AND 2100)
);

INSERT INTO record_setting (setting_id, default_year)
VALUES (1, 2026);

CREATE TABLE hour_record (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activity_id INTEGER NOT NULL REFERENCES activity(id),
    volunteer_id INTEGER NOT NULL REFERENCES volunteer(id),
    activity_type VARCHAR(40) NOT NULL CHECK (
        activity_type IN ('TEACHING', 'COMPANION_READING', 'PLAY', 'DAILY_INTERACTION', 'PASSIVE')
    ),
    activity_date DATE NOT NULL,
    hours NUMERIC(6, 1) NOT NULL CHECK (hours > 0),
    note TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE OR REPLACE FUNCTION set_hour_record_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER hour_record_updated_at_trigger
BEFORE UPDATE ON hour_record
FOR EACH ROW
EXECUTE FUNCTION set_hour_record_updated_at();

COMMIT;
