spring:
  application:
    name: backend

  config:
    import: optional:file:.env[.properties]

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/volunteer_record_system}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:ul6y3fu0 }

server:
  port: ${PORT:8080}

logging:
  level:
    org.springframework.boot.context.config: DEBUG
