spring:
  application:
    name: backend

  config:
    import: optional:file:.env[.properties]

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/volunteer_record_system}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:}

server:
  port: ${PORT:8080}
